### ISSUE TITLE
Moving speed  of cartographer hector

### ISSUE THREAD

**Issue by sunmk2006** [tu-darmstadt-ros-pkg/cartographer_hector_tracker#1]
hello,I have implemented the rotation laser according to your cartographer hector configuration, but can only move at a very slow speed. How did you solve it?

**Comment by kdaun** [comment]
Hi, to understand your issue we need some more information:
Which version of cartographer/cartographer_ros are you using? (Current google master? tu-darmstadt-ros-pkg fork? )
Can you send a link to your launch file?
What is your robot configuration and in which terrain are you operating?

**Comment by sunmk2006** [comment]
Hi,I am using google release cartographer/cartographer_ros 0.2.0,and the launch file is [here](https://github.com/sunmk2006/cartographer_ros/blob/master/spin_laser_bringup.zip), I understand your support for the rotating laser through [the issue#40](https://github.com/googlecartographer/cartographer_ros/issues/40), the conversion node is from [vigir_lidar_proc](https://github.com/team-vigir/vigir_lidar_proc/blob/master/vigir_laserscan_to_pointcloud/src/laserscan_to_pointcloud_node.cpp),it needs tf transform from laser frame to base_link frame,
but the laser is spinning continuously,so using an attached IMU module to measure the posture of the rotating frame，I didn't use mileage information because I wanted to move the rotating laser in my hands.On the basis of your experience, whether it works and how do you measure the attitude of a rotating laser?

**Comment by kdaun** [comment]
Ok, so you are using a handheld device with an IMU and a rotating lidar. To asses your the scenario I require some more information.
What do you mean by
>  but can only move at a very slow speed

? So are you carrying the device in your hands and your only able to walk slowly?
Which IMU and which lidar are you using?

**Comment by sunmk2006** [comment]
Yes, I put in the hands of rotating equipment in indoor mobile, but not in the normal pace, only in accordance with the turtle movement.
The IMU device model is xsens-MTI-G-700,lidar is hokuyo-ust-10lx.

**Comment by kdaun** [comment]
We tried using Cartographer with a single rotating Hokuyo UTM-30LX, however results for trajectories with high accelerations were not too good as well. This sounds rather similar to your experience.

Using either two Hokuyo UTM-30LX or a single Velodyne VLP16 in combination with the optimizing trajectory builder (https://github.com/tu-darmstadt-ros-pkg/cartographer/tree/rc17_wo_tsdf) significantly improved the quality of the results for our scenario.

**Comment by sunmk2006** [comment]
Do you mean that this is due to the sparsity of low frequency laser data?I have two questions. How do you get the real-time angle data of the turntable, the steering gear coder or the gyroscope? Where is the difference between your catographer and Google's cartographer? Is there any documentation?

**Comment by kdaun** [comment]
Sparsity of the scans is one issue, another one is observability. Usually, locating a planar scan (as provided by the 10LX or the 30LX) in a 3D environment is not a fully constrained problem. Therefore, the combination of multiple planar scans is necessary (see e.g. [LOAM by Zhang and Singh](http://www.roboticsproceedings.org/rss10/p07.pdf)). Having a VLP16 or two 30LX relaxes this problem to some extend.
Our version of Cartographer is based on a scan matching formulation somewhat similar to the LOAM approach, which has been removed from the current Cartographer version (see [here](https://github.com/tu-darmstadt-ros-pkg/cartographer/blob/rc17_wo_tsdf/cartographer/mapping_3d/robust_optimizing_local_trajectory_builder.cc)). However, this code is highly experimental, there is no documentation and work on it probably won't continue until fall.
For computing the transform between the base_link and the rotating lidar we use a time-synchronized motor driver.
For the orientation of the robot we use Cartographer.
